### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by 413x1nkp** [sinkaroid/jigoku#4]
I was just trying to normally use this tool, i chose my txt that contains all urls, selected posts and original sizes and this error came out
Sorry if my request seems dumb and nooby (it's cause i am) but i have no idea how to fix this. All requirements are satisfied (as far as i know). Sorry for being an idiot but i'd really appreciate your help!!!!!!!!!!!
> Traceback (most recent call last):
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
>     raise new_e
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
>     conn.connect()
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
>     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
>     ssl_sock = ssl_wrap_socket(
>                ^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
>     return self.sslsocket_class._create(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
>     self.do_handshake()
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
>     self._sslobj.do_handshake()
> ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
>     raise reraise(type(error), error, _stacktrace)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
>     raise value.with_traceback(tb)
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
>     raise new_e
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
>     conn.connect()
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
>     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
>     ssl_sock = ssl_wrap_socket(
>                ^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
>     return self.sslsocket_class._create(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
>     self.do_handshake()
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
>     self._sslobj.do_handshake()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\client\scrape_posts.py", line 42, in download_from_multiple_posts
>     res = requests.get(line.replace("\n", ""), headers=jgx.with_headers)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Scripts\jigoku.exe\__main__.py", line 7, in <module>
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\app.py", line 37, in main
>     download_from_multiple_posts(file, select_type)
>   File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\client\scrape_posts.py", line 189, in download_from_multiple_posts
>     print(f"{line} Retrying because {e} in 3 seconds.. | {res.status_code}")
>                                                           ^^^
> UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

**Comment by sinkaroid** [comment]
Hi, when i look your error trace it's seems the requests connection pool were broke it, 
is your internet not blocked or such? working as intended with related imageboards site that you want download it?

- May i have the screenshot of your `file.txt`? since this covers plenty of booru site, I don't know exactly what cause the error if no proof given
- Whenever it's fail to download, a `failed.log` also have been rewriting in this module, can I have that one as well

**Comment by 413x1nkp** [comment]
> Hi, when i look your error trace it's seems the requests connection pool were broke it, is your internet not blocked or such? working as intended with related imageboards site that you want download it?
> 
> * May i have the screenshot of your `file.txt`? since this covers plenty of booru site, I don't know exactly what cause the error if no proof given
> * Whenever it's fail to download, a `failed.log` also have been rewriting in this module, can I have that one as well

There are pretty naughty e621 urls in my file.txt
![image](https://github.com/sinkaroid/jigoku/assets/79400603/325be5d2-426f-4fe9-9a82-64723cde123f)
(pls dont make funm of me)
Also e621 doesn't work in my country without proxies, i just thought they're included in your code.... is there a quick fix for me?

**Comment by sinkaroid** [comment]
There is no additional fix, because you interacts it wrong, 
`/pools` are considered multiple pages, don't mix it with another `/posts`.
You could read this https://github.com/sinkaroid/jigoku#phrases

Your cases should separated with 2 files, eg:
- posts.txt, and choose the multiple post prompt
```
https://e621.net/posts/3950099?q=lazysnout+girly 
https://e621.net/posts/3997708?q=lazysnout+girly 
https://e621.net/posts/3630899?q=lazysnout+girly
https://e621.net/posts/3538301?q=parent%3A3538301
https://e621.net/posts/3228398?q=lazysnout+girly
https://e621.net/posts/3110350?q=lazysnout+girly
https://e621.net/posts/3085210?pool_id=26762
https://e621.net/posts/3085204?pool_id=26762
https://e621.net/posts/3085199?pool_id=26762
https://e621.net/posts/3085197?pool_id=26762
```

- pages.txt, and choose multiple pages
and `posts?` with no followup id considered as pages.
```
https://e621.net/pools/29779
https://e621.net/posts?tags=naomi-tyan
https://e621.net/pools/33075
```

**Comment by sinkaroid** [comment]
Hope this solved, I'll remake this clunky user engagement later, so everything should be done with single file and no prompt needed

**Comment by 413x1nkp** [comment]
> Hope this solved, I'll remake this clunky user engagement later, so everything should be done with single file and no prompt needed

Sadly no

Still getting

```
Traceback (most recent call last):
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\client\scrape_posts.py", line 42, in download_from_multiple_posts
    res = requests.get(line.replace("\n", ""), headers=jgx.with_headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Scripts\jigoku.exe\__main__.py", line 7, in <module>
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\app.py", line 37, in main
    download_from_multiple_posts(file, select_type)
  File "C:\Users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\jigoku\client\scrape_posts.py", line 189, in download_from_multiple_posts
    print(f"{line} Retrying because {e} in 3 seconds.. | {res.status_code}")
                                                          ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
```
No prompt being needed sounds nice, i wish you best luck with that!!!!
But i still think that the problem is no proxies, e621 isn't accessible with just regular internet connection in my country, so i use google chrome's plugins for them, not sure if proxies are implemented in your code though, might be my fault but i don't have any standalone vpns like proton nordvpn etc, so i'd prefer proxies much more.

**Comment by sinkaroid** [comment]
> There is no additional fix, because you interacts it wrong,

Certainly, that was your next step should be like that, the thing is you have to make your connection pool is not broke first, 
There is still no benefits when I applied proxy on this module, maybe next time

Have you tried:
- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp or 
- https://1.1.1.1/

Currently this is the solution to make e621 works on your end

**Comment by 413x1nkp** [comment]
> > There is no additional fix, because you interacts it wrong,
> 
> Certainly, that was your next step should be like that, the thing is you have to make your connection pool is not broke first, There is still no benefits when I applied proxy on this module, maybe next time
> 
> Have you tried:
> 
> * https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp or
> * https://1.1.1.1/
> 
> Currently this is the solution to make e621 works on your end

yeah no, sadly none of vpns work. and even if they did, the speed would be extremely low

wish there could be proxy settings ngl, that'd make it all 10x easier.
but anyway, thanks for trying to help me!

take care! :)
